### ISSUE TITLE
Listing directory screen

### ISSUE THREAD

**Issue by diavrank** [kdydesign/vue-electron#8]
Hello, when I run my application I got this:

![image](https://user-images.githubusercontent.com/39581375/111390058-b7ee2580-8677-11eb-989b-0217db9b41d1.png)

Logs:

````shell

┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/6a31dac0-292f-4ffb-be46-cac3d284ddb2
  For help, see: https://nodejs.org/en/docs/inspector
  
┗ ----------------------------

┏ Electron -------------------

  Installing Devtron from node_modules/devtron
  
┗ ----------------------------

┏ Electron -------------------

  (electron) 'BrowserWindow.getDevToolsExtensions' is deprecated and will be removed. Please use 'session.getAllExtensions' instead.
  
┗ ----------------------------

┏ Electron -------------------

  (electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.
  
┗ ----------------------------

┏ Electron -------------------

  (node:56147) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
  
┗ ----------------------------

┏ Electron -------------------

  (node:56147) UnhandledPromiseRejectionWarning: Error: The path to the extension in 'loadExtension' must be absolute
      at Function.addExtension (electron/js2c/browser_init.js:161:278)
      at Function.addDevToolsExtension (electron/js2c/browser_init.js:225:1028)
      at Object.exports.install (webpack:///./node_modules/devtron/api.js?:13:35)
      at eval (webpack:///./src/main/index.dev.js?:9:71)
  
┗ ----------------------------

┏ Electron -------------------

  (node:56147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:56147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  
┗ ----------------------------

┏ Electron -------------------

  (node:56147) ExtensionLoadWarning: Warnings loading extension at /Users/diavrank/Library/Application Support/Electron/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 

````

Any idea why this happen?

Before this, I had to install `eslint-friendly-formatter` and `eslint` because it needed them.

**Notes:**

- Mac OS 11.2.2
- Node 12.18.4
- Cloned repo from here.

**Comment by diavrank** [comment]
I already fixed it. I had to configure some rules in `webpack.renderer.config.js`:

````javascript

rules: [
      {
        test: /\.scss$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader']
      },
      {
        test: /\.sass$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader?indentedSyntax']
      },
      {
        test: /\.less$/,
        use: ['vue-style-loader', 'css-loader', 'less-loader']
      },
      {
        test: /\.css$/,
        use: ['vue-style-loader', 'css-loader']
      },
      {
        test: /\.html$/,
        use: 'vue-html-loader'
      },
      {
        test: /\.js$/,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.node$/,
        use: 'node-loader'
      },
      {
        test: /\.vue$/,
        use: {
          loader: 'vue-loader',
          options: {
            extractCSS: process.env.NODE_ENV === 'production',
            loaders: {
              sass: 'vue-style-loader!css-loader!sass-loader?indentedSyntax=1',
              scss: 'vue-style-loader!css-loader!sass-loader',
              less: 'vue-style-loader!css-loader!less-loader'
            }
          }
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'imgs/[name]--[folder].[ext]'
          }
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: 'media/[name]--[folder].[ext]'
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'fonts/[name]--[folder].[ext]'
          }
        }
      }
    ]

````

I removed eslint rule in order to remove it from package.json.

Note that in images rule, I had to add SVG because some plugins that I was using, they include svg files and I got an error that I needed to use an specific loader, so, when I added it, the error has gone.
